# Generated by Django 4.2.15 on 2024-08-29 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("io_storages", "0018_alter_azureblobexportstorage_project_and_more"),
        ("io_storages", "0019_aperturedb"),
    ]

    operations = []
